name: Mirroring su GitLab

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  mirror-to-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice (history completa)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fondamentale per scaricare tutti i branch, i tag e la cronologia completa

      - name: Push su GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          # SOSTITUISCI questo URL con il percorso del tuo repo su GitLab (es. tuo-utente/tuo-repo.git)
          GITLAB_URL="https://oauth2:${GITLAB_TOKEN}@git.tools.mia-platform.eu/clients/mia-platform/demo/demo-companies/digital-platform-c/external-pipeline/configurations.git"
          
          # Esegue il push di tutti i branch e tag, rimuovendo quelli eliminati (--prune)
          git push --prune "$GITLAB_URL" "+refs/heads/*:refs/heads/*" "+refs/tags/*:refs/tags/*"
